### ISSUE TITLE
Chart information is not rendered properly.

### ISSUE THREAD

**Issue by saravanancomsc** [PredixDev/px-vis-pie-chart#15]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
![image](https://cloud.githubusercontent.com/assets/3395175/20061161/aea70f70-a524-11e6-8cdd-d82bdf71222a.png)
Actual :

![image](https://cloud.githubusercontent.com/assets/3395175/20061201/d7f62032-a524-11e6-9f9c-82b05aa4fa36.png)

## Steps to reproduce the problem:
1) Downloaded bower dependency.
2) Start your grunt server
3) Open the index.html in bower_components\px-vis-pie-chart\index.html

**Comment by benoitjchevalier** [comment]
Hi, 

I cannot reproduce this issue when doing a clean install of the repo. Please make sure your bower dependencies are up to date.

**Comment by saravanancomsc** [comment]
Send me your SSO we will discuss, I am too working in GE

**Comment by benoitjchevalier** [comment]
Hi,

we'd rather keep the conversations public if possible. Are you still experiencing issues?

**Comment by saravanancomsc** [comment]
Yes, I am still having issues

**Comment by saravanancomsc** [comment]
Can you send me you config of pie-chart

**Comment by benoitjchevalier** [comment]
this is an example: 

```
<px-vis-pie-chart
            id="chart"
            chart-data="{{data}}"
            show-title
            margin='{ "top": "10", "bottom": "10", "left": "0", "right": "0" }'
            series-config='{
                "mySerie" :{"xAxisUnit": "pints",
                "y": "y",
                "x": "x"}
                }'
            >
            </px-vis-pie-chart>
```

actual seriesConfig will change depending on your data
