### ISSUE TITLE
Chart register does not display in correct order. 

### ISSUE THREAD

**Issue by clementchi** [PredixDev/px-vis-pie-chart#16]
Hi,

When we pass sorted data into the chart, the chart will not display the register according to the sorted order. I attached a screen shot below. 

![screen shot 2016-11-08 at 4 03 54 pm](https://cloud.githubusercontent.com/assets/997551/20123064/69bed0a2-a5d1-11e6-9388-93c79b10a051.png)

**Comment by benoitjchevalier** [comment]
As discussed I think we should automatically sort the register based on % (in_getInternalRegisterData)

**Comment by benoitjchevalier** [comment]
I think this has been fixed.... Please reopen if this is still a problem
