### ISSUE TITLE
Chart color and register color out of sync

### ISSUE THREAD

**Issue by clementchi** [PredixDev/px-vis-pie-chart#17]
Hi,

After we keep the chart running for some time. The chart colors and the register colors will become out of sync. In our app, we update the chart periodically and we will push a new array into the chart if there is update to the array. After a while, the color will be out of sync. 

![screen shot 2016-09-27 at 11 56 15 am](https://cloud.githubusercontent.com/assets/997551/20123172/1b9c71e4-a5d2-11e6-8dfc-4f62dcf285d9.png)

**Comment by benoitjchevalier** [comment]
We need to fix. Can be part of #9

**Comment by benoitjchevalier** [comment]
fixed in 0.3.3
