### ISSUE TITLE
The total count will be pushed down if the register list is too long. 

### ISSUE THREAD

**Issue by clementchi** [PredixDev/px-vis-pie-chart#18]
Hi,

When there are many register, the "total" number in the middle of the chart will be pushed out side the chart. 

![screen shot 2016-11-07 at 2 17 52 pm](https://cloud.githubusercontent.com/assets/997551/20123355/69bd18b4-a5d3-11e6-8a70-88e1983841e3.png)

![screen shot 2016-10-17 at 11 01 09 am](https://cloud.githubusercontent.com/assets/997551/20123634/529653c4-a5d5-11e6-9084-f6c48d7f6224.png)

**Comment by benoitjchevalier** [comment]
we need to check if that is still the case with new major

**Comment by benoitjchevalier** [comment]
hopefully should be fixed by #35 in upcoming v1.0.0 release

**Comment by clementchi** [comment]
thank you Ben

⁣Sent from TypeApp ​

**Comment by benoitjchevalier** [comment]
Should be fixed with 1.0.0 release. PLease reopen if you're still having issues
