### ISSUE TITLE
Chart register does not flex following the 3 up card container size

### ISSUE THREAD

**Issue by clementchi** [PredixDev/px-vis-pie-chart#19]
Hi, 

We placed pie chart inside the 3 up card container. We have to limit the width of the chart to fit inside the 3 up card container. When we display on bigger monitor, the 3 up card flex however the register still have truncation and does not flex following the container size change. 

If we fix the chart size width, if the register text length is longer the text will wrap to the 2nd line. 

![screen shot 2016-09-27 at 11 56 15 am](https://cloud.githubusercontent.com/assets/997551/20123596/1f3a2d20-a5d5-11e6-999a-f49c76c67265.png)
<img width="364" alt="screen shot 2016-10-19 at 5 52 47 pm" src="https://cloud.githubusercontent.com/assets/997551/20123604/2b567a96-a5d5-11e6-92a6-59a7b913643c.png">

**Comment by benoitjchevalier** [comment]
We need to at least expose truncation options (easy), ideally have a smart truncation system (hard)

**Comment by benoitjchevalier** [comment]
truncation has been exposed in 0.3.3, allowing developers to dynamically truncate the register.

We might still want to investigate the behavior of the chart in a 3 up card in the new major version (it should fit when not using preventResize, it might currently overflow)
