### ISSUE TITLE
series color order doesnt works

### ISSUE THREAD

**Issue by vagusX** [PredixDev/px-vis-pie-chart#20]
version: "0.2.11"

```html

<px-vis-pie-chart
  series-color-order='["dv-light-green","dv-light-orange","dv-light-red"]'
  chart-data='[{"percentage":"60","x":15,"y":"IPA"},{"percentage":"20","x":1,"y":"Pils"},    
{"percentage":"20","x":1,"y":"Lager"}]'
...></px-vis-pie-chart>
```

## Code examples [CodePen](http://codepen.io/vagusX/pen/jVwbYM)

**Comment by randyaskin** [comment]
The CodePen you posted seems to be showing the series in the order you specified (green, orange, red) - maybe this has been fixed? If so, please close this issue.

**Comment by vagusX** [comment]
@randyaskin it seems work fine. close it
