### ISSUE TITLE
Dependency px-vis#~0.7.0 No tag found.

### ISSUE THREAD

**Issue by jiqiang** [PredixDev/px-vis-pie-chart#22]
# Submit an Issue

Hi,

## Expected behavior and actual behavior:
Expected: px-vis-pie-chart should be installed with its dependencies.
Actual: bower px-vis#~0.7.0       ENORESTARGET No tag found that was able to satisfy ~0.7.0
## Steps to reproduce the problem:
bower install --save px-vis-pie-chart
## Screenshots (_optional, but very helpful_):
![screen shot 2016-11-30 at 1 47 34 pm](https://cloud.githubusercontent.com/assets/938491/20737890/a18c0fb6-b703-11e6-9c9d-1f3f6ab392a6.png)

**Comment by benoitjchevalier** [comment]
Thank you for your feedback, we are aware of the problem and working on releasing px-vis 0.7.0 soon. I'll update this post as soon as it is available

**Comment by benoitjchevalier** [comment]
px-vis 0.7.0 is now released, the issue should be fixed!
