### ISSUE TITLE
While I am using this in my application I am  getting baseColors is not defined  error and pie chart is not getting displayed. Please help.

### ISSUE THREAD

**Issue by AsheeshShekhawat** [PredixDev/px-vis-pie-chart#25]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by benoitjchevalier** [comment]
Hello,

We noticed the issue yesterday and it should be fixed already. Please try refetching px-vis and px-vis-pie-chart, this should solve the issue.
