### ISSUE TITLE
Title can be misplaced when using preventResize in new major

### ISSUE THREAD

**Issue by benoitjchevalier** [PredixDev/px-vis-pie-chart#26]

**Comment by nonmetalhail** [comment]
Let's move the titles from HTML to SVG. Should make positioning easier and allow for export to an image; will need to move theming check

**Comment by benoitjchevalier** [comment]
related to #35

**Comment by davidsteinberger** [comment]
Will that make it into v1.0.0?

**Comment by benoitjchevalier** [comment]
very unlikely. This can be a post v1.0.0 stuff though (v1.0.0 aimed at this Friday, 10th March)

**Comment by davidsteinberger** [comment]
Hm, correct me if I'm wrong, but there's no real workaround present:

The assumption is that _width_ equals _height_ to get the title close to being centered. The recent change to to the registers makes the register's width same as the width of the chart. So as the user increases the width of the chart (e.g. to provide more horizontal space for the register) the chart grows vertically too and will take up more real-estate.

**Comment by benoitjchevalier** [comment]
I don't think increasing the width of the chart will lead it to increasing its height. The chart uses a behavior (PxVisBehaviorChart.circleChart) to figure out what side is the smallest and use that value to draw the chart, so that the drawing itself always has the same width and height.

The width being passed down to the register should only be used for checking if the register needs toolbars, not actually setting its width. Saying that I just spotted a bug where the scrollbars don't dynamically get added/removed when resizing the width, will try to have a look.

Let me know if I missed your point

**Comment by davidsteinberger** [comment]
I did not say the chart will grow by itself, but to get the title centered you have to increase it's height.
Here's a demo: https://github.com/davidsteinberger/px-vis-pie-chart/tree/title-issue

**Comment by benoitjchevalier** [comment]
Thanks for clarifying, I see now. Yeah this needs to be fixed pre-v1.0.0, looking pretty bad

**Comment by benoitjchevalier** [comment]
@davidsteinberger I got around decoupling some stuff between vis-pie and pie-chart, including moving the title to be directly within the SVG rather than manually placing an HTML element, which should hopefully prevent a lot of headaches in the future (not the first time title was causing issue). This should also help ensuring tooltip and popover are correctly positioned when using some different sets of margins (they use to sometimes go wrong in certain configurations).
All in latest master in vis and pie-chart

Also updated the "official" demo (index.html) which can make it easier to test some configs

**Comment by davidsteinberger** [comment]
I'm impressed. Not only does this fix my issues w/ the title, it also finally fixes the positioning of the toolips (#11) for me, as the black tooltips are now placed more reliable. The tooltip-width for the one that's shown onclick is still strange, but I'm going to comment on that in #11.

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
