### ISSUE TITLE
Query on Pie Chart

### ISSUE THREAD

**Issue by anundinesh** [PredixDev/px-vis-pie-chart#27]
I'm getting an exception Px.d3.pie() is not function in px-vis-pie.html, legends alone are loaded at the moment, pie chart is not loading. Could you please help me to understand the issue?

**Comment by benoitjchevalier** [comment]
Can you give more information? What version are you using? Have you run `bower install`?

**Comment by anundinesh** [comment]
[px-vis-pie-chart::_flattenBehaviorsList]: behavior is null, check for missing or 404 import - I'm getting this warning and still facing the issue of loading the pie chart, legends are loading.
Yes, I've run bower install and version is 0.4.2. Kindly let me know what would be the issue

**Comment by anundinesh** [comment]
This has been fixed when we run bower install of pie chart, it didn't load the png file in px-vis-pie-chart
