### ISSUE TITLE
Title go out from the donut when long

### ISSUE THREAD

**Issue by jennifergouin** [PredixDev/px-vis-pie-chart#29]
Hi,

## Expected behavior and actual behavior:
While using a px-vis-pie-chart in donut way, the title is in the middle. 
Expected : the title does not go out from the donut when it is long, the font-size is reduced to stay inside the donut
Actual : if the title is long, the title go out from the donut

## Steps to reproduce the problem:
Create a donut with a total value equal to 9999999 mm

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
version : 0.4.2
browser : chrome

## Screenshots (_optional, but very helpful_):
![capture d ecran 2017-02-24 a 14 05 36](https://cloud.githubusercontent.com/assets/25823228/23304499/696314c4-fa9a-11e6-8f4d-cc4249d3f213.png)

## Code examples help us better understand the issue
Code from codepen to reproduce
`<div style='width:450px'><px-vis-pie-chart chart-data='[{"percentage":"26","x":150000,"y":"IPA"},{"percentage":"2","x":1,"y":"Pils"},{"percentage":"2","x":1,"y":"Lager"},{"percentage":"14","x":8,"y":"Lambic"},{"percentage":"21","x":12,"y":"Stout"},{"percentage":"12","x":7,"y":"Pale Ale"},{"percentage":"16","x":9,"y":"Porter"},{"percentage":"7","x":4,"y":"Heffeweisse"}]' use-percentage="true" donut="true" show-title="true" width="759.046875" height="350" register-config='{"width":150,"type":"vertical"}' margin='{"top":"10","bottom":"10","left":"0","right":"0"}' series-config='{"mySerie":{"xAxisUnit":"pints","y":"y","x":"x"}}'></px-vis-pie-chart></div>
`

**Comment by benoitjchevalier** [comment]
could be fixed by #34
