### ISSUE TITLE
Strange behavior while resizing

### ISSUE THREAD

**Issue by jennifergouin** [PredixDev/px-vis-pie-chart#30]
Hi,

## Expected behavior and actual behavior:
While resizing multiple time the window with a donut inside, the behavior is very strange : the donut is growing again and again at each resize...

## Steps to reproduce the problem:
Create a donut, and resize the window multiple times

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
v0.4.2
Chrome

## Screenshots (_optional, but very helpful_):
Before
![capture d ecran 2017-02-24 a 14 05 36](https://cloud.githubusercontent.com/assets/25823228/23304661/3c3d888e-fa9b-11e6-92c6-0848d91b8986.png)

After multiple resizing 
![capture d ecran 2017-02-24 a 14 11 08](https://cloud.githubusercontent.com/assets/25823228/23304663/3ef6e0fc-fa9b-11e6-90c3-49d6393c7cc2.png)

To explain the difference, the size of the title is the same in each image, but the size of the donut is really bigger on the second one

## Code examples help us better understand the issue 
You can directly take the code from codepen, no strange configuration, it is always like that

**Comment by benoitjchevalier** [comment]
This should be fixed in the upcoming release, v1.0.0

**Comment by jennifergouin** [comment]
Oh great !
When the release is planned ?

**Comment by benoitjchevalier** [comment]
Friday (10th of March). I can't test it on codepen before the release actually happened but can't see the issue locally. Let's double check on friday!

**Comment by benoitjchevalier** [comment]
Should be fixed with 1.0.0 release. Please reopen if you still experience issues
