### ISSUE TITLE
Total is displayed with the high precision (which may totally destroy the layout)

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis-pie-chart#32]
## Expected behavior and actual behavior:

The chart uses `toFixed()` to round slices to a configurable amount of digits after the decimal point.
I'd expect _total_ to be treated in the same way (at least provide an option for that).

## Steps to reproduce the problem:

Use any v1.x.x version of px-vis-pie with slices like: `[4.05, 0, 0, 4.35]`

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

v1.x.x

## Screenshots (_optional, but very helpful_):

![screen shot 2017-03-07 at 17 21 19](https://cloud.githubusercontent.com/assets/385430/23666433/4db27c0a-035b-11e7-925e-5c8aadef8e68.png)

**Comment by benoitjchevalier** [comment]
Ok, I've added this, total now uses toFixed(this.decimalPercentage)

**Comment by davidsteinberger** [comment]
Thanks!

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
