### ISSUE TITLE
Not able to customize title font-size using --px-vis-pie-title-font-size and --px-vis-pie-title-value-font-size

### ISSUE THREAD

**Issue by AnkitGE** [PredixDev/px-vis-pie-chart#42]
Scenario 1 - Not able to customize title font-size using --px-vis-pie-title-font-size and --px-vis-pie-title-value-font-size using these custom properties. 
Scenario 2 - Need to reduce the thickness of pie/donut. Not able to find any option.

Please see below to see the actual vs expected behavior as per use-case needed -
 
Actual Behavior -
![image](https://user-images.githubusercontent.com/28588406/29906681-23a7e846-8e34-11e7-93b3-34e8fa3d7b72.png)

Expected Behavior -
![image](https://user-images.githubusercontent.com/28588406/29906702-506df4f6-8e34-11e7-9661-d77397079120.png)

**Comment by benoitjchevalier** [comment]
Hello,

I just tested your 'scenario 1' and managed to change the font size using the css variables (those are not component properties, see [this](https://www.predix-ui.com/#/develop/migrate/theme) for more information).

The thickness of the doughnut can be configured through `innerRadius`, more info in the [API](https://www.predix-ui.com/#/elements/vis/px-vis-pie-chart:property-innerRadius)

**Comment by AnkitGE** [comment]
@benoitjchevalier Can you please share some sample code or example for 'scenario 1' implementation.
