### ISSUE TITLE
Color-series-list property name mistake : "color" and "series" are reversed

### ISSUE THREAD

**Issue by stephanepilla** [PredixDev/px-vis-pie-chart#43]
Hello,

I think the name of the property `color-series-list` is wrong in the px-vis-pie-chart component.

It should be `series-color-list` as defined in px-vis-behavior-colors.html (from px-vis).

**Comment by ssaini24** [comment]
Can i take this issue?

**Comment by stephanepilla** [comment]
I have created a pull request for that issue : it is just a property name change in the local dom of the component

**Comment by benoitjchevalier** [comment]
Thanks for the PR, merged and available in v2.1.3
